export const USER_LOGGING_IN = 'USER_LOGGING_IN'
export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const RECV_ERROR = 'RECV_ERROR';
export const REQ_DATA = 'REQ_DATA';
export const RECV_DATA_PROFILE = 'RECV_DATA_PROFILE';
export const UPDATED_PROFILE = "UPDATED_PROFILE";
export const GENERAL_REQUEST = 'GENERAL_REQUEST';
export const RECV_DATA_TIMETABLE = 'RECV_DATA_TIMETABLE';
export const RECV_PATIENTS = 'RECV_PATIENTS';
export const HOST_NAME = 'http://107.170.246.203:1337';
// export const HOST_NAME = 'http://localhost:1337';
